# Generated by Django 4.1.1 on 2023-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('tops', 'Tops'), ('shorts', 'Shorts'), ('pants', 'Pants'), ('underwear', 'Underwear'), ('accessories', 'Accessories'), ('suit', 'Suit'), ('caps', 'Caps'), ('socks', 'Socks'), ('shoes', 'Shoes'), ('helmet', 'Helmet')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=10),
        ),
    ]
