# Generated by Django 4.1.1 on 2023-08-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('tops', 'tops'), ('shorts', 'shorts'), ('pants', 'pants'), ('underwear', 'underwear'), ('accessories', 'accessories'), ('suit', 'suit'), ('caps', 'caps'), ('socks', 'socks'), ('shoes', 'shoes'), ('helmet', 'helmet')], max_length=20),
        ),
    ]
